services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    container_name: redis-jgw40g44w08sggss4ckck04g-124819842338
    restart: unless-stopped
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.420.6
      - coolify.applicationId=1
      - coolify.type=application
      - coolify.name=redis-jgw40g44w08sggss4ckck04g-124819842338
      - coolify.resourceName=sumedhav0501-paywisemain-ygwcgksw8gc4404sg0wgc4o8
      - coolify.projectName=paywise
      - coolify.serviceName=sumedhav0501-paywisemain-ygwcgksw8gc4404sg0wgc4o8
      - coolify.environmentName=production
      - coolify.pullRequestId=0
    networks:
      jgw40g44w08sggss4ckck04g: null
    environment:
      COOLIFY_BRANCH: '"main"'
      COOLIFY_RESOURCE_UUID: jgw40g44w08sggss4ckck04g
      COOLIFY_CONTAINER_NAME: redis-jgw40g44w08sggss4ckck04g-124819842338
      SERVICE_URL_MEILISEARCH: 'https://api.dhonchak.dev'
      SERVICE_FQDN_MEILISEARCH: api.dhonchak.dev
      SERVICE_URL_BACKEND: 'https://api.dhonchak.dev'
      SERVICE_FQDN_BACKEND: api.dhonchak.dev
 
  meilisearch:
    build:
      context: .
      dockerfile_inline: "FROM getmeili/meilisearch:v1.6.2\nCOPY meili_dumps/meilisearch-dump.dump /tmp/meilisearch-dump.dump\n"
    container_name: meilisearch-jgw40g44w08sggss4ckck04g-124819856333
    environment:
      MEILI_ENV: production
      MEILI_MASTER_KEY: '${MEILI_MASTER_KEY}'
      COOLIFY_BRANCH: '"main"'
      COOLIFY_RESOURCE_UUID: jgw40g44w08sggss4ckck04g
      COOLIFY_CONTAINER_NAME: meilisearch-jgw40g44w08sggss4ckck04g-124819856333
      SERVICE_URL_MEILISEARCH: 'https://api.dhonchak.dev'
      SERVICE_FQDN_MEILISEARCH: api.dhonchak.dev
      SERVICE_URL_BACKEND: 'https://api.dhonchak.dev'
      SERVICE_FQDN_BACKEND: api.dhonchak.dev
      COOLIFY_URL: 'https://api.dhonchak.dev'
      COOLIFY_FQDN: api.dhonchak.dev
    # Removed external port exposure - only accessible internally
    expose:
      - '7700'
    entrypoint: "sh -c \"\n  echo 'DEBUG: Checking if dump file exists in container:';\n  ls -la /tmp/meilisearch-dump.dump 2>/dev/null || echo 'Dump file not found in /tmp/';\n  if [ ! -f /meili_data/.restore_done ]; then\n    echo 'Checking existing data...';\n    if [ -d /meili_data/data.ms ]; then\n      echo 'Existing database directory found, deleting...';\n      rm -rf /meili_data/data.ms;\n    fi;\n    echo 'Restoring from dump...';\n    meilisearch --import-dump /tmp/meilisearch-dump.dump &&\n    touch /meili_data/.restore_done;\n  fi;\n  meilisearch\n\"\n"
    volumes:
      - 'jgw40g44w08sggss4ckck04g_meili-data-vol:/meili_data'
    depends_on:
      - redis
    restart: unless-stopped
    labels:
      # Keep only Coolify management labels - remove all Traefik/Caddy routing labels
      - coolify.managed=true
      - coolify.version=4.0.0-beta.420.6
      - coolify.applicationId=1
      - coolify.type=application
      - coolify.name=meilisearch-jgw40g44w08sggss4ckck04g-124819856333
      - coolify.resourceName=sumedhav0501-paywisemain-ygwcgksw8gc4404sg0wgc4o8
      - coolify.projectName=paywise
      - coolify.serviceName=sumedhav0501-paywisemain-ygwcgksw8gc4404sg0wgc4o8
      - coolify.environmentName=production
      - coolify.pullRequestId=0
    networks:
      jgw40g44w08sggss4ckck04g: null
 
  backend:
    build: ./backend
    ports:
      - '3001:3001'
    environment:
      NODE_ENV: production
      PORT: '3001'
      COOLIFY_BRANCH: '"main"'
      COOLIFY_RESOURCE_UUID: jgw40g44w08sggss4ckck04g
      COOLIFY_CONTAINER_NAME: backend-jgw40g44w08sggss4ckck04g-124819876955
      SERVICE_URL_MEILISEARCH: 'https://api.dhonchak.dev'
      SERVICE_FQDN_MEILISEARCH: api.dhonchak.dev
      SERVICE_URL_BACKEND: 'https://api.dhonchak.dev'
      SERVICE_FQDN_BACKEND: api.dhonchak.dev
      COOLIFY_URL: 'https://api.dhonchak.dev'
      COOLIFY_FQDN: api.dhonchak.dev
    depends_on:
      - redis
      - meilisearch
    container_name: backend-jgw40g44w08sggss4ckck04g-124819876955
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`api.dhonchak.dev`)
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.tls=true
      - traefik.http.services.api.loadbalancer.server.port=3001
      - 'traefik.http.middlewares.cors.headers.accesscontrolalloworigin=https://paywiselease.netlify.app'
      - 'traefik.http.middlewares.cors.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST,DELETE'
      - 'traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*'
      - traefik.http.routers.api.middlewares=cors@docker
      - coolify.managed=true
      - coolify.version=4.0.0-beta.420.6
      - coolify.applicationId=1
      - coolify.type=application
      - coolify.name=backend-jgw40g44w08sggss4ckck04g-124819876955
      - coolify.resourceName=sumedhav0501-paywisemain-ygwcgksw8gc4404sg0wgc4o8
      - coolify.projectName=paywise
      - coolify.serviceName=sumedhav0501-paywisemain-ygwcgksw8gc4404sg0wgc4o8
      - coolify.environmentName=production
      - coolify.pullRequestId=0
      - traefik.enable=true
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.http-0-jgw40g44w08sggss4ckck04g-backend.entryPoints=http
      - traefik.http.routers.http-0-jgw40g44w08sggss4ckck04g-backend.middlewares=redirect-to-https
      - 'traefik.http.routers.http-0-jgw40g44w08sggss4ckck04g-backend.rule=Host(`api.dhonchak.dev`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-jgw40g44w08sggss4ckck04g-backend.entryPoints=https
      - 'traefik.http.routers.https-0-jgw40g44w08sggss4ckck04g-backend.middlewares=gzip,cors'
      - 'traefik.http.routers.https-0-jgw40g44w08sggss4ckck04g-backend.rule=Host(`api.dhonchak.dev`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-jgw40g44w08sggss4ckck04g-backend.tls.certresolver=letsencrypt
      - traefik.http.routers.https-0-jgw40g44w08sggss4ckck04g-backend.tls=true
      - 'caddy_0.encode=zstd gzip'
      - 'caddy_0.handle_path.0_reverse_proxy={{upstreams}}'
      - 'caddy_0.handle_path=/*'
      - caddy_0.header=-Server
      - 'caddy_0.try_files={path} /index.html /index.php'
      - 'caddy_0=https://api.dhonchak.dev'
      - caddy_ingress_network=jgw40g44w08sggss4ckck04g
    networks:
      jgw40g44w08sggss4ckck04g: null
 
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      BACKEND_URL: '${BACKEND_HOST}'
      BACKEND_HOST: '${BACKEND_HOST}'
      COOLIFY_BRANCH: '"main"'
      COOLIFY_RESOURCE_UUID: jgw40g44w08sggss4ckck04g
      COOLIFY_CONTAINER_NAME: frontend-jgw40g44w08sggss4ckck04g-124819879428
      SERVICE_URL_MEILISEARCH: 'https://api.dhonchak.dev'
      SERVICE_FQDN_MEILISEARCH: api.dhonchak.dev
      SERVICE_URL_BACKEND: 'https://api.dhonchak.dev'
      SERVICE_FQDN_BACKEND: api.dhonchak.dev
    stdin_open: true
    tty: true
    depends_on:
      - backend
    container_name: frontend-jgw40g44w08sggss4ckck04g-124819879428
    restart: unless-stopped
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.420.6
      - coolify.applicationId=1
      - coolify.type=application
      - coolify.name=frontend-jgw40g44w08sggss4ckck04g-124819879428
      - coolify.resourceName=sumedhav0501-paywisemain-ygwcgksw8gc4404sg0wgc4o8
      - coolify.projectName=paywise
      - coolify.serviceName=sumedhav0501-paywisemain-ygwcgksw8gc4404sg0wgc4o8
      - coolify.environmentName=production
      - coolify.pullRequestId=0
    networks:
      jgw40g44w08sggss4ckck04g: null
 
volumes:
  jgw40g44w08sggss4ckck04g_meili-data-vol:
    name: jgw40g44w08sggss4ckck04g_meili-data-vol
 
networks:
  jgw40g44w08sggss4ckck04g:
    name: jgw40g44w08sggss4ckck04g
    external: true
 
configs: {}
secrets: {}