version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'

  meilisearch:
    image: getmeili/meilisearch:v1.6.2
    container_name: meilisearch
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    ports:
      - '7700:7700'
    volumes:
      - novetedlease_meili_data:/meili_data

  backend:
    build: ./backend
    container_name: backend
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - MEILI_PAGINATION_MAX_TOTAL_HITS=20000
      - REDIS_HOST=redis
      - MEILISEARCH_HOST=http://meilisearch:7700
      - BACKEND_HOST=${BACKEND_HOST}
      - FRONTEND_URL=${FRONTEND_URL}
      - PFX_CERT_PATH=${PFX_CERT_PATH}
      - PFX_CERT_PASSWORD=${PFX_CERT_PASSWORD}
      - API_ENDPOINT=${API_ENDPOINT}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - API_SCOPE=${API_SCOPE}
    depends_on:
      - redis
      - meilisearch

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - BACKEND_URL=${BACKEND_HOST}
    stdin_open: true
    tty: true

volumes:
  novetedlease_meili_data:
    external: true
