services:
  redis:
    image: 'redis:latest'
    container_name: redis-jgw40g44w08sggss4ckck04g-124819842338
    restart: unless-stopped
    expose:
      - '6379'
    networks:
      - jgw40g44w08sggss4ckck04g
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.420.6
      - coolify.applicationId=1
      - coolify.type=application
      - coolify.name=redis-jgw40g44w08sggss4ckck04g-124819842338

  meilisearch:
    build:
      context: .
      dockerfile_inline: "FROM getmeili/meilisearch:v1.6.2\nCOPY meili_dumps/meilisearch-dump.dump /tmp/meilisearch-dump.dump\n"
    container_name: meilisearch-jgw40g44w08sggss4ckck04g-124819856333
    restart: unless-stopped
    expose:
      - '7700'
    volumes:
      - 'jgw40g44w08sggss4ckck04g_meili-data-vol:/meili_data'
    depends_on:
      - redis
    networks:
      - jgw40g44w08sggss4ckck04g
    environment:
      MEILI_ENV: production
      MEILI_MASTER_KEY: '${MEILI_MASTER_KEY}'
      # Internal service communication
      MEILISEARCH_INTERNAL_URL: 'http://meilisearch:7700'
      # External URLs for API responses
      MEILISEARCH_EXTERNAL_URL: 'https://meilisearch.dhonchak.dev'
    entrypoint: |
      sh -c "
        if [ ! -f /meili_data/.restore_done ]; then
          echo 'Restoring from dump...';
          if [ -d /meili_data/data.ms ]; then
            rm -rf /meili_data/data.ms;
          fi;
          meilisearch --import-dump /tmp/meilisearch-dump.dump &&
          touch /meili_data/.restore_done;
        fi;
        meilisearch
      "
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.420.6
      - coolify.applicationId=1
      - coolify.type=application
      - coolify.name=meilisearch-jgw40g44w08sggss4ckck04g-124819856333

  backend:
    build: ./backend
    container_name: backend-jgw40g44w08sggss4ckck04g-124819876955
    restart: unless-stopped
    expose:
      - '3001'
    depends_on:
      - redis
      - meilisearch
    networks:
      - jgw40g44w08sggss4ckck04g
    environment:
      NODE_ENV: production
      PORT: '3001'
      # Internal service URLs (for server-to-server communication)
      REDIS_URL: 'redis://redis:6379'
      MEILISEARCH_URL: 'http://meilisearch:7700'
      MEILISEARCH_MASTER_KEY: '${MEILI_MASTER_KEY}'
      # External URLs (for client responses/redirects)
      BACKEND_URL: 'https://api.dhonchak.dev'
      MEILISEARCH_EXTERNAL_URL: 'https://meilisearch.dhonchak.dev'
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.420.6
      - coolify.applicationId=1
      - coolify.type=application
      - coolify.name=backend-jgw40g44w08sggss4ckck04g-124819876955

  frontend:
    build: ./frontend
    container_name: frontend-jgw40g44w08sggss4ckck04g-124819879428
    restart: unless-stopped
    expose:
      - '3000'
    depends_on:
      - backend
    networks:
      - jgw40g44w08sggss4ckck04g
    environment:
      NODE_ENV: production
      # Frontend should use external URLs
      REACT_APP_BACKEND_URL: 'https://api.dhonchak.dev'
      REACT_APP_MEILISEARCH_URL: 'https://meilisearch.dhonchak.dev'
      BACKEND_HOST: 'https://api.dhonchak.dev'
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.420.6
      - coolify.applicationId=1
      - coolify.type=application
      - coolify.name=frontend-jgw40g44w08sggss4ckck04g-124819879428

volumes:
  jgw40g44w08sggss4ckck04g_meili-data-vol:
    name: jgw40g44w08sggss4ckck04g_meili-data-vol

networks:
  jgw40g44w08sggss4ckck04g:
    name: jgw40g44w08sggss4ckck04g
    external: true
