import React from 'react'

const Disclaimer = () => {
  return (
    <div className='p-4 xs:p-4 sm:p-6 md:p-8 lg:px-16 py-4 bg-[#003E511A] text-[11px] xs:text-xs md:text-sm lg:text-md 3xl:text-2xl'>
      <p> <span className='font-bold text-primary' >Disclaimer :</span> The results generated by this novated lease calculator are for illustrative purposes only and based on the information you provide. Figures are estimates and should not be considered final or binding. Actual costs and savings may vary depending on your financial situation, tax bracket, and government policies. Vehicle images are for reference only and may not reflect available colours or models. Terms and conditions apply. </p>
    </div>
  )
}

export default Disclaimer
